
module.exports = {
  'ACTION': 'action',
  'BOOKS_REQUEST': 'books:request',
  'BOOKS_SUCCESS': 'books:success',
  'BOOKS_FAILURE': 'books:failure',
  'BOOK_REQUEST' : 'book:request',
  'BOOK_SUCCESS' : 'book:success',
  'BOOK_EDIT_REQUEST' : 'book:edit:request',
  'BOOK_EDIT_SUCCESS' : 'book:edit:success',
  'BOOK_DELETE_REQUEST' : 'book:delete:request',
  'BOOK_DELETE_SUCCESS' : 'book:delete:success',
  'COLLECTIONS_REQUEST': 'collections:request',
  'COLLECTIONS_SUCCESS': 'collections:success',
  'COLLECTIONS_FAILURE': 'collections:failure',
  'COLLECTION_ADD_REQUEST': 'collection:add:request',
  'COLLECTION_EDIT_REQUEST': 'collection:edit:request',
  'COLLECTION_DELETE_REQUEST': 'collection:delete:request',
  'LIBRARIES_REQUEST': 'libraries:request',
  'LIBRARIES_SUCCESS': 'libraries:success',
  'LIBRARIES_FAILURE': 'libraries:failure',
  'LIBRARY_ADD_REQUEST': 'library:add:request',
  'LIBRARY_EDIT_REQUEST': 'library:edit:request',
  'LIBRARY_DELETE_REQUEST': 'library:delete:request',
};
